name: Android CI

on:
  push:
    branches: [ "master", "capy/**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android NDK
      run: |
        sdkmanager --install "ndk;26.1.10909125"
        sdkmanager --install "cmake;3.22.1"
    
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: xenia-android-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Generate Build Info
      run: |
        echo "## Build Information" >> $GITHUB_STEP_SUMMARY
        echo "- Build Date: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- APK Size (Debug): $(du -h app/build/outputs/apk/debug/app-debug.apk | cut -f1)" >> $GITHUB_STEP_SUMMARY
